quarkus:
  - name: quarkus
    image:
      repository: ghcr.io/forsakringskassan/template-quarkus-app
      tag: snapshot

apache:
  - name: apache
    image:
      repository: ghcr.io/forsakringskassan/designsystem-user-app
      tag: snapshot

route:
  paths:
    - path: /api
      pathType: Prefix
      backend: quarkus
    - path: /
      pathType: Prefix
      backend: apache

