replicaCount: 1

quarkus:
  - name: quarkus
    image:
      repository: ghcr.io/forsakringskassan/template-quarkus-app
      tag: snapshot
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 8080

apache:
  - name: apache
    image:
      repository: ghcr.io/forsakringskassan/designsystem-user-app
      tag: snapshot
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  hosts:
    - paths:
        - path: /api
          pathType: Prefix
          backend: quarkus
        - path: /
          pathType: Prefix
          backend: apache

